version: "3.8"

services:
  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db

  app:
    build: ./backend
    ports:
      - "6800:6800"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/docu-maintainer
      PORT: 6800

volumes:
  mongo-data:
