apiVersion: apps/v1
kind: Deployment
metadata:
  name: three-tier-backend
  labels:
    app: three-tier-backend
  namespace: "{{ .Values.namespace }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: three-tier-backend
  template:
    metadata:
      labels:
        app: three-tier-backend
    spec:
      containers:
        - name: three-tier-backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 6800
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: MONGO_URI

            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: PORT
