apiVersion: apps/v1
kind: Deployment
metadata:
  name: three-tier-backend
  labels:
    app: three-tier-backend
  namespace: three-tier-app-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: three-tier-backend
  template:
    metadata:
      labels:
        app: three-tier-backend
    spec:
      containers:
        - name: three-tier-backend
          image: docker.io/vivekranjan040/three-tier-backend:v5
          ports:
            - containerPort: 6800
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: MONGO_URI

            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: PORT
