apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: three-tier-app-ns
spec:
  selector:
    app: three-tier-backend
  ports:
    - port: 80
      targetPort: 6800
  type: NodePort
