name: Backend
on:
  workflow_dispatch:

jobs:
  Test-code:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Test
        run: echo "Backend test passed"